project:
  type: website

website:
  title: "data with derek"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/drkrodriguez/datawithderek
      - icon: linkedin
        href: https://www.linkedin.com/in/fjsrodriguez/
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

